### ISSUE TITLE
 DFG-Dataset

### ISSUE THREAD

**Issue by lihaosheng191240022** [hjlllll/DexFuncGrasp#2]
"Amazing Work! Could you please provide a documentation explaining the meaning of each parameter in the dataset? Thank you very much."

**Comment by hjlllll** [comment]
<img width="329" alt="image" src="https://github.com/user-attachments/assets/9dcf10b2-94ef-4d22-8da3-816383786e59">
hello, thanks for your interest, rtj means {r,t,j}, which r means the rotation matrix of hand palm orientation, t means xyz of hand palm and j means joint angles of shadowhand joints.

**Comment by tianyuwang01** [comment]
What is the order of the shadowhand joints in your dataset?
