### ISSUE TITLE
If it is possible to change another robotic dexterous hand?

### ISSUE THREAD

**Issue by CodingCatMountain** [hjlllll/DexFuncGrasp#3]
Awesome work! @hjlllll . May I ask about if it is possible to change another robotic dexterous hand, e.g., Allegro hand? Looking forward to your reply.

**Comment by hjlllll** [comment]
Thanks for your attention, Yes, I provide a demo of annotate different dexterous hand in [shadow_dataset_human_shadow_add_issacgym_system_pytorch3d_mesh_new_dataset_multi_dexterous.py], but only use angle mapping method, it can be changed using retargeting method to annotate better poses.

**Comment by CodingCatMountain** [comment]
Thanks @hjlllll
